baseURL = "https://sofiakodar.github.io/"
title = "sofiakodar.github.io"

theme = "PaperMod"

[markup.goldmark.renderer]
  unsafe = true
  
[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true
  author = "Sofia"

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 10